-- =====================================================
-- LOVE LENS - Core Database Schema
-- Clean, simplified structure for relationship surveys
-- Run this in Supabase SQL Editor
-- =====================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- TABLE 1: USERS
-- Stores basic user information with anonymous keys
-- =====================================================
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_key TEXT UNIQUE NOT NULL, -- LOVE-XXXX-XXXX format
  category TEXT NOT NULL, -- single, committed, engaged, married, recently_ended
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_active TIMESTAMPTZ DEFAULT NOW(),
  
  -- Survey status
  survey_completed BOOLEAN DEFAULT FALSE,
  survey_completed_at TIMESTAMPTZ,
  
  -- Report status
  report_unlocked BOOLEAN DEFAULT TRUE, -- Default true for immediate access
  report_unlocked_at TIMESTAMPTZ,
  unlock_method TEXT, -- 'auto', 'whatsapp_share', 'coupon', 'admin'
  
  -- Anonymous analytics (privacy-safe)
  device_type TEXT, -- mobile, tablet, desktop
  os_name TEXT,
  browser_name TEXT,
  session_count INTEGER DEFAULT 1,
  
  CONSTRAINT valid_category CHECK (category IN ('single', 'committed', 'engaged', 'married', 'recently_ended'))
);

-- =====================================================
-- TABLE 2: SURVEY_SUBMISSIONS
-- Stores complete survey data with scores
-- =====================================================
CREATE TABLE IF NOT EXISTS survey_submissions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  user_key TEXT NOT NULL,
  category TEXT NOT NULL,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  
  -- Survey data (JSONB for flexibility)
  questions_answers JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- Format: [{"question_id": "q1", "question_text": "...", "answer_id": "o1", "answer_text": "...", "score": 4, "tags": [...], "weight": 1}]
  
  -- Calculated scores
  raw_score NUMERIC(10,2) DEFAULT 0,
  max_possible_score NUMERIC(10,2) DEFAULT 0,
  normalized_score NUMERIC(4,2) DEFAULT 0, -- 1.0 to 10.0
  
  -- Subscores (1-10 scale)
  communication_score NUMERIC(4,2),
  trust_score NUMERIC(4,2),
  intimacy_score NUMERIC(4,2),
  conflict_score NUMERIC(4,2),
  future_alignment_score NUMERIC(4,2),
  finances_score NUMERIC(4,2),
  
  -- Risk assessment
  breakup_risk_score NUMERIC(4,2), -- 0.0 to 1.0
  breakup_risk_label TEXT, -- Low, Moderate, High
  
  -- Flags
  has_abuse_flag BOOLEAN DEFAULT FALSE,
  has_trust_issues BOOLEAN DEFAULT FALSE,
  has_conflict_issues BOOLEAN DEFAULT FALSE,
  has_intimacy_issues BOOLEAN DEFAULT FALSE,
  has_finance_issues BOOLEAN DEFAULT FALSE,
  
  -- Report insights (generated by backend)
  relationship_archetype TEXT, -- "The Power Couple", "The Steady Builders", etc.
  percentile_rank INTEGER, -- Better than X% of users
  strengths JSONB DEFAULT '[]'::jsonb,
  concerns JSONB DEFAULT '[]'::jsonb,
  recommendations JSONB DEFAULT '[]'::jsonb,
  
  -- Metadata
  total_questions INTEGER DEFAULT 0,
  time_to_complete_seconds INTEGER,
  
  CONSTRAINT valid_normalized_score CHECK (normalized_score >= 1.0 AND normalized_score <= 10.0)
);

-- =====================================================
-- TABLE 3: CHAT_CONVERSATIONS
-- Stores AI chatbot conversations
-- =====================================================
CREATE TABLE IF NOT EXISTS chat_conversations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  user_key TEXT NOT NULL,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Conversation data
  messages JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- Format: [{"role": "user|assistant|system", "content": "...", "timestamp": "...", "tokens": 123}]
  
  -- Metadata
  total_messages INTEGER DEFAULT 0,
  total_tokens_used INTEGER DEFAULT 0,
  ai_model TEXT DEFAULT 'gpt-4',
  
  -- Safety & monitoring
  has_crisis_keywords BOOLEAN DEFAULT FALSE,
  professional_referral_triggered BOOLEAN DEFAULT FALSE,
  conversation_sentiment TEXT -- positive, neutral, negative, crisis
);

-- =====================================================
-- INDEXES for performance
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_users_user_key ON users(user_key);
CREATE INDEX IF NOT EXISTS idx_users_category ON users(category);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_submissions_user_id ON survey_submissions(user_id);
CREATE INDEX IF NOT EXISTS idx_submissions_user_key ON survey_submissions(user_key);
CREATE INDEX IF NOT EXISTS idx_submissions_category ON survey_submissions(category);
CREATE INDEX IF NOT EXISTS idx_submissions_normalized_score ON survey_submissions(normalized_score DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_created_at ON survey_submissions(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_chat_user_id ON chat_conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_user_key ON chat_conversations(user_key);
CREATE INDEX IF NOT EXISTS idx_chat_created_at ON chat_conversations(created_at DESC);

-- =====================================================
-- UPDATED_AT trigger function
-- =====================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply triggers
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_chat_updated_at ON chat_conversations;
CREATE TRIGGER update_chat_updated_at
  BEFORE UPDATE ON chat_conversations
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- ANALYTICS VIEW (for global statistics)
-- =====================================================
CREATE OR REPLACE VIEW global_stats AS
SELECT
  COUNT(DISTINCT u.id) as total_users,
  COUNT(DISTINCT CASE WHEN u.survey_completed THEN u.id END) as completed_surveys,
  ROUND(AVG(s.normalized_score)::numeric, 2) as avg_overall_score,
  ROUND(AVG(s.communication_score)::numeric, 2) as avg_communication_score,
  ROUND(AVG(s.trust_score)::numeric, 2) as avg_trust_score,
  ROUND(AVG(s.intimacy_score)::numeric, 2) as avg_intimacy_score,
  ROUND(AVG(s.conflict_score)::numeric, 2) as avg_conflict_score,
  ROUND(AVG(s.future_alignment_score)::numeric, 2) as avg_future_alignment_score,
  ROUND(AVG(s.finances_score)::numeric, 2) as avg_finances_score,
  COUNT(CASE WHEN s.breakup_risk_label = 'High' THEN 1 END) as high_risk_count,
  COUNT(CASE WHEN s.breakup_risk_label = 'Moderate' THEN 1 END) as moderate_risk_count,
  COUNT(CASE WHEN s.breakup_risk_label = 'Low' THEN 1 END) as low_risk_count,
  u.category,
  COUNT(*) as category_count
FROM users u
LEFT JOIN survey_submissions s ON u.id = s.user_id
GROUP BY u.category;

-- =====================================================
-- CATEGORY STATS VIEW (for comparisons)
-- =====================================================
CREATE OR REPLACE VIEW category_stats AS
SELECT
  category,
  COUNT(*) as total_submissions,
  ROUND(AVG(normalized_score)::numeric, 2) as avg_score,
  ROUND(AVG(communication_score)::numeric, 2) as avg_communication,
  ROUND(AVG(trust_score)::numeric, 2) as avg_trust,
  ROUND(AVG(intimacy_score)::numeric, 2) as avg_intimacy,
  ROUND(AVG(conflict_score)::numeric, 2) as avg_conflict,
  ROUND(AVG(future_alignment_score)::numeric, 2) as avg_future_alignment,
  ROUND(AVG(finances_score)::numeric, 2) as avg_finances,
  ROUND(AVG(breakup_risk_score)::numeric, 2) as avg_breakup_risk
FROM survey_submissions
WHERE completed_at IS NOT NULL
GROUP BY category;

-- =====================================================
-- SUCCESS MESSAGE
-- =====================================================
SELECT 'Database schema created successfully!' as status;

